### ISSUE TITLE
HTML format: Index page

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#121]
@steveswinsburg we would like an index page like this so that faculty can use it as an easy way to navigate through the archive files.

[Index.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1278508/Index.html.txt)

Please let me know if you have any questions.

**Comment by steveswinsburg** [comment]
Hi @caconstantino, this is proving really difficult to do, especially with the iframe. I'm going to start with a collapsible tree menu which will show the top level headings and then directories and files underneath, and see how we go here.

**Comment by cacostantino** [comment]
OK.

**Comment by steveswinsburg** [comment]
I've added a top level index page. This is not entirely what you had in the request, however given time constraints is the best we can do so far. With a bit more time this could be enhanced and the iframe on the right added. There is a class that pulls it all together called IndexBuilder which is called at the end of the archive. This can be easily modified to your requirements.

**Comment by cacostantino** [comment]
@steveswinsburg - this is really just a duplication of the view of the folder structure and doesn't look as "pretty" as my view of the folder structure in Finder (Mac) so I don't think we'll want to use it as is. Do you think this is something Asha can work on?

**Comment by steveswinsburg** [comment]
@cacostantino yes, Asha can continue this work. I have written this so it can be extended.
