### ISSUE TITLE
HTML format for Announcements

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#122]
This is the HTML layout we want for Announcements.

[Announcements.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282515/Announcements.html.txt)

Please let me know if you have any questions.

**Comment by cacostantino** [comment]
I'm confused by the subpages here. Where are the "2" and "26" subfolders coming from? 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/29150601/30546530-d567f222-9c5a-11e7-9bfe-e94d06d1c6f5.png">

**Comment by cacostantino** [comment]
I see the problem. The date in the announcement was originally formatted as 1/26/15 can these be changed so that subfolders are not created?

**Comment by cacostantino** [comment]
We need a Announcements list page as an "index" to link everything together, and link to Index page #121.
[Announcements_List.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1311756/Announcements_List.html.txt)

**Comment by steveswinsburg** [comment]
@amiedavis see sanitiser method which will strip the /, which are causing the extra directory names.

**Comment by steveswinsburg** [comment]
Actually I have resolved this in the archiver service itself, pushing a commit now.

**Comment by steveswinsburg** [comment]
Once this is backported it is ready to test again.

**Comment by cacostantino** [comment]
Subfolder issue has been resolved per today's QA.

**Comment by cacostantino** [comment]
@steveswinsburg I don't see an Announcements_list page.

**Comment by amiedavis** [comment]
@cacostantino unfortunately I missed that, have just added it and created a PR @steveswinsburg

**Comment by steveswinsburg** [comment]
Merged. Thanks @amiedavis
