### ISSUE TITLE
HTML format for Chat

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#123]
This is the HTML layout we want for Chat.

[Chat.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282533/Chat.html.txt)

Please let me know if you have any questions.

**Comment by amiedavis** [comment]
@cacostantino by default, you can only fetch 100 chat messages at a time, which is why we have them saved in blocks at the moment (0-99, 100-199, etc). This also prevents us from ending up with a huge file if there are hundreds of chat messages. Are you happy for us to keep this format? We could provide a top level index.html page that links all html pages together.

**Comment by cacostantino** [comment]
Yes, that makes sense. Yes, please provide a top-level page to link all the chat pages together.

**Comment by cacostantino** [comment]
I think we should change "[owner] ([date]):" to "<b>[owner] ([date]):</b>" so that it is easier to read.

**Comment by cacostantino** [comment]
@steveswinsburg - please change **[owner] ([date]):** to be in bold so that's it's easier to read.

**Comment by cacostantino** [comment]
@steveswinsburg 
The user and date in bold - √
The index page - √
The organization of messages 1-100 and 100-107, doesn't make sense. 

1. This should be 101-107, bc the 100th message isn't duplicated. 
2. The oldest 6 messages are on the page "100-107" and the newest 100 are on the "1-100" page. It should be reversed so that I can read the messages in chronological order from the top of "1-100" to the bottom of "100-700.

See attached zip as the example.

[STAT+325+01+_+STAT+625+01+_F15_-2c9c7cf55ea4ca4d015ea5ad6f5f0005.zip](https://github.com/steveswinsburg/sakai-archiver/files/1322346/STAT.325.01._.STAT.625.01._F15_-2c9c7cf55ea4ca4d015ea5ad6f5f0005.zip)

**Comment by steveswinsburg** [comment]
Ordering and numbering has been fixed by @amiedavis
