### ISSUE TITLE
HTML format for Forums

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#124]
This is the HTML layout we want for Forums.

[Forums.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282580/Forums.html.txt)

Please let me know if you have any questions.

**Comment by steveswinsburg** [comment]
Hi @cacostantino, if there are multiple topics per forum, should these all be in the one page? Do you think that the context of the threaded discussion may get lost? What if there was a top level page for each forum and thread so you could drill into it?

**Comment by cacostantino** [comment]
I think that will work as long as the faculty member can navigate to them without hunting through the Forums folder.

**Comment by cacostantino** [comment]
There is no "index" page that links to each forum so there is nothing to connect to Index page #121.

**Comment by cacostantino** [comment]
I have to review the forums pages with David to see if the topics and threads are OK. I think they may be more confusing this way.

**Comment by cacostantino** [comment]
We need a Forums list page as an "index" to link everything together, and link to Index page #121 

[Forums_List.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1311727/Forums_List.html.txt)

**Comment by cacostantino** [comment]
Can we also add a breadcrumb trail to the top of the topics and responses pages so that one can navigate through all of the files without using the back button?
<img width="397" alt="image" src="https://user-images.githubusercontent.com/29150601/30557741-45a3ccec-9c7d-11e7-95e9-2fa111beb411.png">

**Comment by steveswinsburg** [comment]
Breadcrumbs are going to have to be left as a nice to have (new ticket?). Index should sort this out by linking all forums under the same folder.
