### ISSUE TITLE
HTML format for Assignments

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#125]
This is the HTML layout we want for the two Assignments pages

Assignment details - 
[Assignments1.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282590/Assignments1.html.txt)

Assignment submissions - 
[Assignments2.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282600/Assignments2.html.txt)

Please let me know if you have any questions.

**Comment by amiedavis** [comment]
@cacostantino in the submission html, you have submitted attachments but not feedback attachments, is that correct? Do you want feedback attachments at the bottom, or is it unlikely for there to be an attachment as feedback? 
I currently have the submission html being saved under the student's name, with submitted attachments saved under the folder "submission" and feedback attachments saved under the folder "feedback", but only the submission attachments listed in the html.

**Comment by amiedavis** [comment]
@cacostantino another thing I noticed, if the grade scale is something like Pass/Fail, you end up with:
 Maximum score: 0.00 Pass/Fail
Do you want different behaviour depending on the grade scale or is this ok?

**Comment by steveswinsburg** [comment]
@cacostantino the first cut of this is in, however please see the questions from Amie above. Cheers.

**Comment by cacostantino** [comment]
@amiedavis - re: Maximum score: 0.00 Pass/Fail. Can you remove the "0.00?" If not, I think it's fine.

**Comment by cacostantino** [comment]
@amiedavis - Re: Do you want feedback attachments at the bottom, or is it unlikely for there to be an attachment as feedback?  I think we left this off because we didn't think it was likely to be present. However, let's include it just in case.

**Comment by amiedavis** [comment]
@cacostantino  Seeing as "Maximum score" only makes sense for the grade point scale, I have changed it so that if it's any of the other scales (Pass/Fail, Checkmark, etc) it says "Grading scale" instead. So for example it could be:

Maximum score: 50.00 Points

or

Grading scale: Pass/Fail

**Comment by steveswinsburg** [comment]
Updates made. Thanks Amie.

**Comment by cacostantino** [comment]
Sounds good, @amiedavis

**Comment by cacostantino** [comment]
We need an Assignment List page that links to all of the assignments.
[Assignment_List.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1311679/Assignment_List.html.txt)

**Comment by cacostantino** [comment]
We also need to add a link to grades.xls in the Assignment_List.html page.

**Comment by cacostantino** [comment]
This looks good.
