### ISSUE TITLE
HTML format for RSS

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#126]
This is the HTML layout we want for RSS.

[RSS.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282612/RSS.html.txt)

Please let me know if you have any questions.

**Comment by steveswinsburg** [comment]
Done.

**Comment by cacostantino** [comment]
News (RSS tool) does not show up in The Archiver tool at all. So I can't test it.

**Comment by steveswinsburg** [comment]
Your environment is missing the 'sakai.simple.rss' from the archiver.tools in sakai.properties. This needs to be added before the tool will show up in the archiver. This is documented in the readme.

**Comment by cacostantino** [comment]
From Asha - "Looks like it is implementation bug. Steve integrated news archiver differently, he written code to get rss(sakai.simple.rss) feed from ToolConfiguration, which is wrong (I guess). Yale has separate tool for news ‘sakai.news’, he supposed to get news from tool - ‘sakai.news’."

**Comment by steveswinsburg** [comment]
hmm, in the work document I put together we discussed the Basic LTI version which is sakai.simple.rss. I'll create you an archiver for the sakai.news tool as well.
