### ISSUE TITLE
HTML format for Syllabus

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#127]
This is the HTML layout we want for Syllabus.

[Syllabus.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282618/Syllabus.html.txt)

Please let me know if you have any questions.

**Comment by amiedavis** [comment]
@cacostantino there are no attachment links in this new layout - is that what you want?

**Comment by cacostantino** [comment]
Sorry, the [syllabus] place holder is meant to be either a link to the syllabus or the body of the syllabus depending on how the course syllabus page was designed by the instructor.

**Comment by cacostantino** [comment]
The only potential issue I see here is the name of the file, e.g. NURS 897 02 (S15).html as it relates to the Index page #121 ticket where I have it as syllabus.html.

**Comment by cacostantino** [comment]
I will add new attachments and test again.

**Comment by cacostantino** [comment]
Attachment came through fine. :)
