### ISSUE TITLE
HTML format for Home

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#128]
This is the HTML layout we want for Home.

[Home.html.txt](https://github.com/steveswinsburg/sakai-archiver/files/1282631/Home.html.txt)

Please let me know if you have any questions.

**Comment by amiedavis** [comment]
Hi @cacostantino, the only real change I can see here is the heading, can you please confirm I'm not missing something?

**Comment by cacostantino** [comment]
Yes, that's correct. The only things we added were CSS and the H1 title.

**Comment by steveswinsburg** [comment]
This should now be done.

**Comment by cacostantino** [comment]
Tested with image. Came through fine. :)
