### ISSUE TITLE
Provide the ability to cancel an archive

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/sakai-archiver#51]
If an error occurs for whatever reason the archive is still in a started state. it should be possible to cancel a running archive from the UI otherwise it requires database intervention.

**Comment by steveswinsburg** [comment]
Done.

**Comment by cacostantino** [comment]
I don't see how/where I can cancel an archive.

**Comment by steveswinsburg** [comment]
One needs to be in progress or have stalled for whatever reason. They are
likely finishing before you can see it.

You could manually set one back to STARTED if you have access to the
database.

The link appears in archive history.

**Comment by steveswinsburg** [comment]
Probably difficult to test if you don't have DB access. I'll close this out.

**Comment by cacostantino** [comment]
FWIW, I was just able to cancel an archive! :)
