### ISSUE TITLE
Explore archive index page possibility

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#55]
Archives may be most usable if faculty are given a single HTML index page that includes links to all of the archived tools, rather than solely a set of folders with content for each tool type. This would be true especially if the default format for archived content is HTML, with links to attached documents.  

(If this would require a significant amount of additional development time, we may need to ignore the idea. )

**Comment by steveswinsburg** [comment]
Is this still required now that we are using HTML? It might be possible to just dump out the top level of each archive's files into a HTML structure but given that each archive is not fully linked up via HTML, that might not be useful.
