### ISSUE TITLE
Make the banner live polling

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/sakai-archiver#58]
**Tasks**
Either make this an ajaxupdateable label or create a REST endpoint for the status and poll the endpoint and update as required

**Comment by cacostantino** [comment]
Is this the same as "Status doesn’t update once archive is complete (still says “archive started”) even once it is completed?" If so, this is HIGH priority.

**Comment by steveswinsburg** [comment]
This is done and will be on m4 later this week.

**Comment by cacostantino** [comment]
This looks good!
