### ISSUE TITLE
Home archive updates

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/sakai-archiver#64]
Parse the html and grab any images, download them, and rewrite the html link to it.

**Comment by steveswinsburg** [comment]
Hey Amie, split out the first bit into separate ticket and you can probably do the second bit.

**Comment by cacostantino** [comment]
Images embedded in the webpage do not appear  -- MEDIUM priority

**Comment by steveswinsburg** [comment]
This is done and will be in m4.

**Comment by cacostantino** [comment]
@steveswinsburg - Image was included in download folder, however, it does not display in the HTML and will not open directly. 

![image](https://user-images.githubusercontent.com/29150601/28090782-8159c596-665b-11e7-9b02-a3f26398188b.png)

**Comment by steveswinsburg** [comment]
@amiedavis could you please check if pngs are coming through ok?

**Comment by steveswinsburg** [comment]
@amiedavis looks like this site: http://ec2-13-58-10-76.us-east-2.compute.amazonaws.com:8080/portal/site/540a0a91-a20d-454b-82e3-e340abe1349d

For some reason, the contents of this file is actually HTML (open it in a Text Editor)
![webinar2](https://user-images.githubusercontent.com/129129/28247671-8549b4ec-6a78-11e7-8835-7304239eec76.png)

Here is the source code in the Home tool itself:

````
<p>This is a custom home page. &nbsp;I will embed an image here also.</p>

<p><img alt="" height="577" src="http://ec2-13-58-10-76.us-east-2.compute.amazonaws.com:8080/access/content/group/4c34aeae-66ee-4d67-97a0-09e74da51cdf/webinar2.png" width="1009" /></p>
````

The HTML that is rendered and put inside the file is the 'Login Required' screen. So I think it is following the link but then asking for a login. This could be to do with the multi threading however the session should be injected. Can you check if the link following for other images is coming through ok?

**Comment by steveswinsburg** [comment]
I think the issue is this line: 
Jsoup.connect(imageSource).ignoreContentType(**true**).execute().bodyAsBytes();

I'll see if I can reproduce locally and fix this.
