### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#75]
1. Change .JSON to .HTML -- HIGH priority
2. Remove Chat from main list of tools - only available to admins -- HIGH priority

**Comment by cacostantino** [comment]
HIGH priority

**Comment by cacostantino** [comment]
3. Remove metadata JSON from Chat (not useful) -- MEDIUM Priority

**Comment by steveswinsburg** [comment]
This was all done in #62, except the admin piece, however admins can only include student content so if an normal instructor was to do it, nothing would be included. I can make it so the tool doesn't appear at all unless admin.

**Comment by steveswinsburg** [comment]
This is ready to test. However please see comment above. Cheers.

**Comment by cacostantino** [comment]
1. Reviewed. Done.
3. Reviewed. Done.

**Comment by cacostantino** [comment]
2. Chat should not be visible to Instructor, only Admin.

**Comment by steveswinsburg** [comment]
Student content is only visible to admins, see #68 .
