### ISSUE TITLE
Access to Archive Tool

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#77]
Access to tool needs to be role specific (only maintainer/instructor/admin) -- HIGH priority

**Comment by steveswinsburg** [comment]
This was done in #66. Let me know if you need any more changes.

**Comment by cacostantino** [comment]
OK, Thanks.

**Comment by steveswinsburg** [comment]
This is ready to test. Cheers.

**Comment by cacostantino** [comment]
Reviewed. Done.
