### ISSUE TITLE
Gradebook

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#78]
All headers should be changed to strip out "!export.header."  -- HIGH priority

See attached file

[gradebook-export_Demo1.xlsx](https://github.com/steveswinsburg/sakai-archiver/files/1098113/gradebook-export_Demo1.xlsx)

**Comment by steveswinsburg** [comment]
This is done and will be on m4 build towards end of the week.

**Comment by cacostantino** [comment]
This looks good.
