### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#79]
Access to tool needs to be role specific (only maintainer/instructor/admin); just like Chat -- MEDIUM priority

**Comment by steveswinsburg** [comment]
Access to the entire archiver is now role specific. Do you mean that only an admin should be able to request the student generated content like in chat?

**Comment by steveswinsburg** [comment]
This is ready to test, however please see question above. Cheers.

**Comment by cacostantino** [comment]
Forum tool should only be visible/usable by admins, not instructor.

**Comment by steveswinsburg** [comment]
The student content of the forum tool should only available to admins by virtue of the previous work around superuser in #44 . Did you want it to disappear completely?
