### ISSUE TITLE
Forums: HTML format

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#83]
Please convert the .json files to .html files. See example below from NURS 897.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/29150601/27693582-d42fadd8-5cb7-11e7-85c1-41dfca6eeade.png">

**Comment by cacostantino** [comment]
Priority: MEDIUM

**Comment by steveswinsburg** [comment]
Hi @cacostantino , this is ready to test and will be on the server tonight. I note there is another Forums HTML issue raised so you might want to wait until that is done, or review this and see where we are at. Cheers.

**Comment by cacostantino** [comment]
Looks good. We still need the HTML layout changed.
