### ISSUE TITLE
Folder Naming

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#84]
1. Course zip file should be named as the course. 
 - Eg. "nurs89702_s15.zip" instead of "38bdefd6-6401-42fc-b1f9-a6d87ad8033a.zip"

2. Tool folder naming should be just the tool name without the prefix "sakai." for all tools.
- Eg. "announcements" instead of "sakai.announcements"

**Comment by cacostantino** [comment]
Priority = HIGH

**Comment by steveswinsburg** [comment]
Second part is tracked at #63. Might merge the two.

**Comment by steveswinsburg** [comment]
When writing the zip file, I'll rename the file so it is the site name (ie nurs89702_s15.zip), however unpacking the zipfile will still make a directory on your computer called 38bdefd6-6401-42fc-b1f9-a6d87ad8033a, is that ok? The reason being that this part has to be unique on the filesystem where the archive is created as it is the unique archive ID.

**Comment by cacostantino** [comment]
@steveswinsburg I've never seen that happen before, as the unpacked folder has always been the same name as the zip file in my experience. It is certainly better than what we have now. Again, this is a HIGH priority item.

**Comment by steveswinsburg** [comment]
#63 is done. About to push in the zip naming.

**Comment by steveswinsburg** [comment]
Zip naming done. @cacostantino I will be rebuilding the server with all of these changes for m5 soon, will send you an email when done and they can all be tested.

**Comment by cacostantino** [comment]
@steveswinsburg 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/29150601/28171460-79f9a8a0-67b6-11e7-91c6-72337eba04e3.png">

As you can see, I archived 4 courses. Can we have the zip file name like the NURS & Developer courses (preferably without the number/letter combo), and have the un-zipped folder have the course name (Nurs89702_s15) instead of "Home"?

**Comment by steveswinsburg** [comment]
Hi @cacostantino I have figured this out. If the zip file only contains one folder (ie you choose just Home or just Anouncements etc) then the zip file is unzipped down to just that folder. So you get just Home or just Announcements.

If the zip file contains two or more then it will leave the intermediary folder. See the attached two exports containing one, then two folders.
[Developer+test+site-two.zip](https://github.com/steveswinsburg/sakai-archiver/files/1151713/Developer.test.site-two.zip)
[Developer+test+site-one.zip](https://github.com/steveswinsburg/sakai-archiver/files/1151714/Developer.test.site-one.zip)

I'll try to get it to always leave the intermediate folder.

**Comment by steveswinsburg** [comment]
@cacostantino how likely is an archive to just contain one tool? I am wondering if I can split this since item zip issue out into its own issue so that we can come back to it later if time permits? Spent a bit of time on it already but it is a bit hairy.

**Comment by cacostantino** [comment]
@steveswinsburg Developer+test+site-two.zip looks good. I don't think it's all that likely to have just one tool. If I were a faculty member looking to archive a course, I would select every tool. I agree with splitting this item.

**Comment by steveswinsburg** [comment]
Split to #112
