### ISSUE TITLE
Photo Roster

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#85]
The photo view should be a PDF just like this PDF:  [photoview_sample.pdf](https://github.com/steveswinsburg/sakai-archiver/files/1113366/photoview_sample.pdf)

The attached PDF was pulled from the "Print" function on the photo/ view on our environment.

![classes v2roster_picturesview](https://user-images.githubusercontent.com/29150601/27707734-698b734a-5ce4-11e7-8805-85f9037678ad.jpeg)

The list view CSV download looks fine.

**Comment by cacostantino** [comment]
Priority = HIGH

**Comment by steveswinsburg** [comment]
This is going to take a while because there is no document to start with. The export from the roster tool cannot be used. I'll have to build a HTML file and then PDF it. Is the PDF essential or would be HTML file be ok?

**Comment by cacostantino** [comment]
@steveswinsburg - yes an HTML is fine. Since this is one of the highest priority items, can you work on this before the LOW and MEDIUM items, please?

**Comment by steveswinsburg** [comment]
OK I have a design for this and this is up next. I needed to get a few of the architectural things done first, mainly #63 and the associated tasks for that so that both the custom photo tool and roster could coexist. Underway!

**Comment by steveswinsburg** [comment]
This is nearing completion and will be on m6.

**Comment by steveswinsburg** [comment]
@cacostantino OK I am going to push up the first cut of some custom HTML for the photo roster export. Since we don't have actual photos (integrates with the Yale Photo Directory), everyone gets the same photo, however it should be rendering in a grid with image and then the data fields underneath. Sample file attached (it's a PDF but the file is actually HTML, I can't attach HTML here)
[roster.pdf](https://github.com/steveswinsburg/sakai-archiver/files/1159180/roster.pdf)

Also rebuilding m6 right now.

**Comment by cacostantino** [comment]
@steveswinsburg - a few things...

1. The metadata fields displaying in your mockup are not the same as in our Photo Roster in Classes*v2. See my attachment for an example of the v2 content. For archival purposes it is probably unnecessary to include SID, although the simplest thing to do here might be to duplicate what's in the v2 view without changes.
2. There's no count of class participants in each role, as there was at the top of the v2 photo roster. 
3. There is also no indication of which class it is: faculty who print this page will not know which term it was taught, etc. 

[Classesv2-Roster-picture-view.pdf](https://github.com/steveswinsburg/sakai-archiver/files/1163569/Classesv2-Roster-picture-view.pdf)

**Comment by steveswinsburg** [comment]
@cacostantino, for 1, my test data doesn't have those fields so they don't show. Do you want them to show even if there is no data?
2 and 3 I am addressing now.

**Comment by steveswinsburg** [comment]
Done. Will push to the AWS server once I have a few more things done.

**Comment by steveswinsburg** [comment]
OK this should be on the AWS server now.

**Comment by cacostantino** [comment]
@steveswinsburg  - it's looking good, but I want to see what it looks like with our actual data. So I'd say it's "Pending Yale environment QA."

**Comment by cacostantino** [comment]
1. Roster-export changes needed:
- Name - student names should be in alphabetical order
- Col - current data is "section" which is not needed; correct data is currently listed under Major.
- Major - current data is "Col"; correct data is currently listed under Year.
- Year - current data is "Major"; correct data is currently listed to the right under no heading.
- Last column with no heading and number data is not needed.

**Comment by cacostantino** [comment]
2. Photo roster HTML changes needed:
- Name - student names should be in alphabetical order
- Col - current data is "section" which is not needed; correct data is currently listed under Major.
- Major - current data is "Col"; correct data is currently listed under Year.
- Year - current data is "Major"; correct data is currently listed to the right under no heading.

**Comment by steveswinsburg** [comment]
Discussed this with Asha a few weeks ago. Your roster code is missing a
line of code from the merge, which means the column headers are out of
whack. Asha was going to resolve this.

This data all comes from the excel export, so once that is sorted out the issues above will be resolved. Also, the sorting of the names is within the roster2 code itself.
