### ISSUE TITLE
Course number and tool name in headers

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#91]
If possible, it would be great to include the course number (for example: SMPL101 (Spring 2017) or NURS 897 02 (S15), plus the tool name, in a header at the top of each tool's HTML index page.  

For instance: in a course named NURS 897 02 (S15), the very top of the page would say:

NURS 897 02 (S15): Forums

for the Forums and Topics data;

NURS 897 02 (S15): Assignments

for the Assignments data.  

The rationale: many of our professors will likely print the HTML pages, and without an identification of the course number and tool name they might get confused about which course/tool the data is for.

**Comment by steveswinsburg** [comment]
Done. Needs backport.

**Comment by steveswinsburg** [comment]
Note that in m5 it still has the toolId in the header eg **NURS 897 02 (S15) (SPRING 2015): sakai.iframe.site** but I have raised #108 to update this.

**Comment by steveswinsburg** [comment]
#108 done so this is ready to go.

**Comment by cacostantino** [comment]
@steveswinsburg will this be in M6 for me to test?

**Comment by steveswinsburg** [comment]
This is in m5 with the exception of the toolname. It still shows the tool id as above. I am almost finished the customised photo roster export and will rebuild m6 then.

**Comment by cacostantino** [comment]
OK, Thanks, Steve.

**Comment by cacostantino** [comment]
This looks good!
