### ISSUE TITLE
Syllabus: Delete start and end dates

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#92]
startDate and endDate are not needed in the Syllabus archive

**Comment by steveswinsburg** [comment]
Done!

**Comment by cacostantino** [comment]
@dah36 - how is this?

<img width="657" alt="image" src="https://user-images.githubusercontent.com/29150601/28329405-b8073662-6bb7-11e7-83b6-5a688e70514c.png">

**Comment by cacostantino** [comment]
@steveswinsburg Let's cancel this one. David and I are looking at the HTML layout of all the tools most holistically and will submit a different ticket.
