### ISSUE TITLE
Syllabus: add link to attachment

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#93]
As you've been doing for other tools, it would be ideal to include a link to any attachments on the Syllabus page HTML itself. 

Rationale: in most cases, the Syllabus content in our instance of Sakai is ONLY the linked Word or PDF file.  There will be no other HTML/text content of importance to faculty.

**Comment by steveswinsburg** [comment]
This is done but not yet on the AWS server so don't test just yet.

**Comment by cacostantino** [comment]
Tested and confirmed. This can be closed.
