### ISSUE TITLE
Chat: remove eid field

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#94]
eid field does not need to be displayed on the Chat archive page.

**Comment by steveswinsburg** [comment]
Done!

**Comment by cacostantino** [comment]
@dah36  - is this what you wanted?

<img width="735" alt="image" src="https://user-images.githubusercontent.com/29150601/28329308-63c35194-6bb7-11e7-83ec-7dc61f222d65.png">

**Comment by cacostantino** [comment]
@steveswinsburg Let's cancel this one. David and I are looking at the HTML layout of all the tools most holistically and will submit a different ticket.
