### ISSUE TITLE
Chat: revised UI suggestion

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#95]
If possible, it would be great to reformat the data fields in the Chat display so that it resembles the attached version. 
![chat-preferred-layout](https://user-images.githubusercontent.com/29129164/27883898-3ee2874e-61a0-11e7-93e9-847e605ef318.png)

**Comment by dah36** [comment]
This is the current layout view for chat, for comparison and identification of the fields.
![chat-current-layout](https://user-images.githubusercontent.com/29129164/27883954-708d6ab6-61a0-11e7-8ea8-c83cadbce473.png)

**Comment by steveswinsburg** [comment]
Closing this one as Christine said there would be different specs coming.
