### ISSUE TITLE
Forums: delete unneeded data fields

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#96]
On Forum summary page, the following data fields can be removed:
- isLocked
- isModerated
- isPostFirst
- openDate
- closeDate
- assocGradebookItemName
- isDraft
- modifiedDate
- modifiedBy

topics
- modifiedDate
- modifier
- isLocked
- isPostFirst
- assocGradebookItemName
- openDate
- closeDate

**Comment by steveswinsburg** [comment]
Done!

**Comment by cacostantino** [comment]
@dah36 - Is this what you are looking for?

<img width="773" alt="image" src="https://user-images.githubusercontent.com/29150601/28329102-95655982-6bb6-11e7-8b71-65801c0cf510.png">

**Comment by cacostantino** [comment]
@steveswinsburg Let's cancel this one. David and I are looking at the HTML layout of all the tools most holistically and will submit a different ticket.
